.TH NEKOTOOLS 1 "Oct 31, 2006" ""
.SH NAME
nekotools \- tools for running Neko programs.
.SH SYNOPSIS
.B nekotools [options]
.SH OPTIONS
.TP
.B server
start a neko web server.  The server can be configured through
.IR "http://localhost:2000/server:config" .
.TP
.BI "boot " file.n
build an standalone executable.
.SH DESCRIPTION
.B nekotools
is a command-line tool to create executables from Neko bytecode.
.SH AUTHOR
Neko is written by Nicolas Cannasse for Motion-Twin.
.SH SEE ALSO
.BR "neko" (1),
.BR "nekoc" (1).
.SH WEB
.IR "https://nekovm.org" .
