.TH NEKOC 1 "Oct 31, 2006" ""
.SH NAME
nekoc \- compile Neko programs to Neko bytecode.
.SH SYNOPSIS
.B nekoc
.I file.neko
.SH DESCRIPTION
.B nekoc
is a command-line compiler which compiles Neko programs into Neko bytecode.
.SH AUTHOR
Neko is written by Nicolas Cannasse for Motion-Twin.
.SH SEE ALSO
.BR "neko" (1),
.BR "nekotools" (1).
.SH WEB
.IR "http://nekovm.org" .
