.TH NEKOML 1 "Apr 21, 2016" ""
.SH NAME
nekoml \- compile NekoML programs to Neko bytecode.
.SH SYNOPSIS
.B nekoml
.I file.neko
.SH DESCRIPTION
.B nekoml
is a command-line compiler which compiles NekoML programs to Neko bytecode.
.SH AUTHOR
Neko is written by Nicolas Cannasse for Motion-Twin.
.SH SEE ALSO
.BR "neko" (1),
.BR "nekoc" (1),
.BR "nekotools" (1).
.SH WEB
.IR "http://nekovm.org" .
