.TH NEKO 1 "Oct 31, 2006" ""
.SH NAME
neko \- Neko virtual machine.
.SH SYNOPSIS
.B neko
.I file.n
.SH DESCRIPTION
.B neko
is a command-line tool for running Neko bytecode.
.PP
Neko can be called from the Apache2 web server via the module
mod_neko2 contained in package libapache2-mod-neko.
.SH AUTHOR
Neko is written by Nicolas Cannasse for Motion-Twin.
.SH SEE ALSO
.BR "nekoc" (1),
.BR "nekotools" (1).
.SH WEB
.IR "http://nekovm.org" .
